Repository kubernetes-sigs/externalip-webhook, pull requests merged in 2022-03, with the labels that each got.

#19 modify webhook failurePolicy to Fail
  config/webhook/manifests.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#18 Add a feature to restrict by user
  README.md
  config/webhook/webhook.yaml
  go.mod
  go.sum
  main.go
  pkg/validator/service_validator.go
  pkg/validator/service_validator_test.go
Labels: cncf-cla: yes, approved, lgtm, size/L

#21 Make webhook/manifests.yaml in sync with service_validator.go
  Makefile
  config/webhook/manifests.yaml
  pkg/validator/service_validator.go
  pkg/validator/service_validator_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S
